### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
Ah, this is a crazy downgrade

```
Installing collected packages: py3dmol, plbenchmark, plugcli, pansi, gufe, openfe, docker, cryptography, openfe-benchmarks, grolt
    Attempting uninstall: cryptography
      Found existing installation: cryptography 38.0.4
      Uninstalling cryptography-38.0.4:
        Successfully uninstalled cryptography-38.0.4
  Successfully installed cryptography-3.4.8 docker-6.0.1 grolt-1.0.7 gufe-0.4.post37+g789c8fb openfe-0.4.post6+gf1140ea openfe-benchmarks-0.0.0 pansi-2020.7.3 plbenchmark-0.2.1+3.g262633b plugcli-0.0.1 py3dmol-1.8.1
```

**Comment by dotsdl** [comment]
Looks like 3.4.8 is from a year ago. Not as bad as it looks, though for a cryptographic library certainly not preferable. Any idea which package is holding it back?

**Comment by mikemhenry** [comment]
`Requirement already satisfied: cffi>=1.12 in /usr/share/miniconda3/lib/python3.9/site-packages (from cryptography~=3.0->grolt->-r /home/runner/work/fah-alchemy/fah-alchemy/devtools/conda-envs/condaenv.yobl9am9.requirements.txt (line 1)) (1.15.1)` 
and 
` Requirement already satisfied: pycparser in /usr/share/miniconda3/lib/python3.9/site-packages (from cffi>=1.12->cryptography~=3.0->grolt->-r /home/runner/work/fah-alchemy/fah-alchemy/devtools/conda-envs/condaenv.yobl9am9.requirements.txt (line 1)) (2.21)`

seem to indicate that `cffi` is to blame https://foss.heptapod.net/pypy/cffi

**Comment by dotsdl** [comment]
You won't need `grolt` for the Docker image build, so if that's contributing you can axe it. That's only needed for running the `fah-alchemy` test suite.

**Pull request closed without merging**
